// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCclfNJVMLcVK_GnJ1my_-RT__n7ObcGfk',
    appId: '1:568893461500:web:9b35e59c4b25d2d8309879',
    messagingSenderId: '568893461500',
    projectId: 'ev-app-e94d9',
    authDomain: 'ev-app-e94d9.firebaseapp.com',
    storageBucket: 'ev-app-e94d9.appspot.com',
    measurementId: 'G-QSSZCZYJH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfm5GjVTtN1-lH6OyWCEQBoC4O9L-B9mQ',
    appId: '1:568893461500:android:345fd66a5a303b2c309879',
    messagingSenderId: '568893461500',
    projectId: 'ev-app-e94d9',
    storageBucket: 'ev-app-e94d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWITvLXecx-ghnzWQ7jGXb28n1xzp2CW0',
    appId: '1:568893461500:ios:5428487f4171a37c309879',
    messagingSenderId: '568893461500',
    projectId: 'ev-app-e94d9',
    storageBucket: 'ev-app-e94d9.appspot.com',
    iosBundleId: 'com.example.evApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWITvLXecx-ghnzWQ7jGXb28n1xzp2CW0',
    appId: '1:568893461500:ios:5428487f4171a37c309879',
    messagingSenderId: '568893461500',
    projectId: 'ev-app-e94d9',
    storageBucket: 'ev-app-e94d9.appspot.com',
    iosBundleId: 'com.example.evApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCclfNJVMLcVK_GnJ1my_-RT__n7ObcGfk',
    appId: '1:568893461500:web:365bfb17bca76837309879',
    messagingSenderId: '568893461500',
    projectId: 'ev-app-e94d9',
    authDomain: 'ev-app-e94d9.firebaseapp.com',
    storageBucket: 'ev-app-e94d9.appspot.com',
    measurementId: 'G-4PPNCLFMQH',
  );
}
